### ISSUE TITLE
contact-form widget doesn't inject recaptcha code

### ISSUE THREAD

**Issue by heldchen** [magento/security-package#26]
the recaptcha code is not used with the contact form widget in custom cms pages.

### Preconditions
1. 2.3.1
2. all composer modules up-to-date

### Steps to reproduce
1. create cms page 
2. include the contact-form widget:
```
{{block class="Magento\Contact\Block\ContactForm" name="contactForm" template="Magento_Contact::form.phtml"}}
``` 
3. in the frontend, visit the page and submit the form

### Expected result
1. recaptcha should be injected and the form properly submitted

### Actual result
1. recaptcha code is missing
2. form is submitted to /contact/index/index
3. error "Incorrect reCAPTCHA" is shown
4. all data entered is lost

**Comment by engcom-Delta** [comment]
With current recaptcha implementation we cannot add it to widget from Content->Pages, only from configuration for specific controllers
Mark this issue as **Feature Request** for further discussion

**Comment by dvoskoboinikov** [comment]
@magento export issue to Jira project MC as Story

**Comment by nathanjosiah** [comment]
There were some pre-requisites to this internally. This issue is currently pending a discussion.

**Comment by nathanjosiah** [comment]
We have ultimately decided not to work on this issue internally right now due to scheduling and commitment reasons. We may decide to do this in the future but for now we will close this issue. You are welcome to open a PR to fix this issue in which case I will happily reopen this.
