### ISSUE TITLE
Display Input When Entering 2FA Code

### ISSUE THREAD

**Issue by mpchadwick** [magento/security-package#36]
The input to enter the 2FA code, (at least with the Google Authenticator provider for sure) obscures the input. This is generally considered security theatre at the cost of usability. At minimum a "show code" checkbox to toggle visibility would be nice, although I think there's no reason to obscure the input at all.

### Preconditions

1. Configure 2FA with Google Authenticator provider

### Steps to reproduce

1. Authenticate successfully with a password

### Expected result

1. I can see the 2FA input while I type it

### Actual result

1. The 2FA input is obscured

**Comment by phoenix128** [comment]
Feature already added to new release.
